### PR TITLE
Fix for issues 846, 944, 945, 946 With TDD

### LINKED ISSUE #846: Some IBAN are invalid
Hey 👋
It seems that some generated IBAN are invalid. Especially the ones for Azerbaijan:
- AZ61042647281602130500843080
- AZ70471180928911231507343770

I'm using [ibantools](https://www.npmjs.com/package/ibantools) to validate iban on my frontend app, and it gives invalid result for those above.

I also checked using this website: https://bank.codes/iban/validate/
Same result... :/ 

EDIT: 
It seems to be the same for some BIC:
- OMPUCPT1MAB
- RXTICPF1475
- LVGACSQ1

### LINKED ISSUE #944: IBAN for Georgia not correct
I got this IBAN generated: `GE10440066518090154041`, which is for Georgia.
According to the [Wikipedia article](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country), the format for an IBAN for Georgia is `GEkk bbcc cccc cccc cccc cc` (which is also used like that in the [lib/iban.js](https://github.com/Marak/faker.js/blob/master/lib/iban.js)), so there should be 2 alpha chars at position 5 and 6, which is not the case for the IBAN that faker generated.

### LINKED ISSUE #945: IBAN for Pakistan not correct
I got this IBAN generated: `PK020OQJ0032302000765089`, which is for Pakistan.
According to the [Wikipedia article](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country), the format for an IBAN for Pakistan is `PKkk bbbb cccc cccc cccc cccc` (which is also used like that in the [lib/iban.js](https://github.com/Marak/faker.js/blob/master/lib/iban.js)), so there should be 4 alpha chars at positions 5 to 8, which is not the case for the IBAN that faker generated.

### LINKED ISSUE #946: IBAN for Turkey not correct
I got this IBAN generated: `TR5443560XTD67065122722770`, which is for Turkey.
According to the [Wikipedia article](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country), the format for an IBAN for Turkey is `TR5443560XTD67065122722770` (which is also used like that in the [lib/iban.js](https://github.com/Marak/faker.js/blob/master/lib/iban.js)), so there should be 5 alpha chars at positions 5 to 9, which is not the case for the IBAN that faker generated.

### PR DESCRIPTION
**Pull request by Moosh-be**
Adding a test to validate the correction of the issues
fix #944 GE IBAN
fix #945 PK IBAN
fix #946 TR IBAN
fix #846 AZ IBAN

### CODE REVIEW

**Comment by Marak** [comment]
@Moosh-be -

Thank you for your contributions.

We are not able to merge failing Pull Requests into `master`, it would break the build.

**Comment by Moosh-be** [comment]
@Marak  I decide to try to patch my self and use review of other to validate my code.

**Comment by Moosh-be** [comment]
@christianbaumann I finaly do it my self, can you check if it's right for you please ?

**Comment by Moosh-be** [comment]
@Marak  for me  I'm ready

**Comment by Marak** [comment]
Merged!

Thank you for your contributions @Moosh-be

**Pull request merged**
