### PR TITLE
Support gender in names

### PR DESCRIPTION
**Pull request by vectart**
This pull request will fix a few problems related to Russian locale:
- `faker.name.firstName()` returns English name
- `faker.name.lastName()` fails because of misprinted `defintions` https://github.com/Marak/faker.js/blob/master/lib/name.js#L20
- `faker.name.findName()` randomly returns male first and female last names and vice verca

In addition, all of these functions will accept `gender` argument.

### CODE REVIEW

**Comment by vectart** [comment]
@Marak I'm not going to bother you, but what do you think of these fixes and improvements?

**Comment by ibrahimyu** [comment]
+1
Sooner or later, we will need to generate names based on gender.

**Comment by kovpack** [comment]
+1 Should be merged

**Comment by kovpack** [comment]
One more thing: using correct `prefix` by it's index is completely wrong way: I suppose, there should be `male_name_prefix` and `female_name_prefix` and fallback to `prefix` for those locales that do not yet support that. Many languages have more than 2 prefixes and I have doubts that their order is and will always be correct (anyway, forcing translators to use some predefined order is wrong approach).

**Comment by Marak** [comment]
@vectart -

Looks OK. I have merged into `master` and will continue to review for upcoming release.

Thank you for your contribution!

**Comment by vectart** [comment]
@Marak thank you for merging!

**Pull request merged**
