### PR TITLE
Add catalog es_MX for Mexico

### PR DESCRIPTION
**Pull request by isortegah**
as you comment on the issue add MX locale #231, add the catalog to Mexico.

### CODE REVIEW

**Comment by Marak** [comment]
muy bueno!

will review and merge this week.

**Comment by isortegah** [comment]
hi good day, a question, the application request must be made?

**Comment by Marak** [comment]
Looks good @isortegah 

Thank you for your contribution :-)

**Comment by bchavez** [comment]
@isortegah @Marak , don't forget to enable "es_MX" in https://github.com/Marak/faker.js/blob/master/lib/locales.js

**Pull request merged**
