### PR TITLE
nep -> ne

### PR DESCRIPTION
**Pull request by Moosh-be**
new try,  like #957 but without rebuild
To solve #956

- [x]     rename nep to ne
- [x]     jslint ok
- [x]     run tests

### CODE REVIEW

**Comment by Marak** [comment]
Can anyone else here verify this PR before we merge? Thank you!

At a quick look, this looks OK to me.

Thank you @Moosh-be !!!

**Comment by Marak** [comment]
@ohcibi - 

Could you do a quick check of this PR? 

I think it's OK.

Just want to double check that we didn't lose any data in the rename.

**Comment by Moosh-be** [comment]
HAlo @ohcibi  

Help to review ,  
Only first commit contain real changes on  2 files.

the second  commit is  only the renaming of directory and  fix indentation 

so  with  hid withespace, you see less fil to check.

https://github.com/Marak/faker.js/pull/976/commits/35d4e79290f5fefa313f6bd0279a2c53bd410607?diff=split&w=1

I don't know  some renaming arer taken ... as rename, and other as an deleted file and a created one (same name)

**Comment by Moosh-be** [comment]
Someone to Review my PR ?

**Comment by ohcibi** [comment]
Sorry guys. I wasn't realizing that I had a @mention notification. I'll try to have a look at this this week.

**Comment by ohcibi** [comment]
@Moosh-be thanks for the effort. To properly rename you need to rename first and then add the changes. Could you please perform the following steps:

```
git fetch
git rebase origin/master
git reset origin/master
git stash -u
git mv <the Directory renaming>
git commit -m <rename directory commit message>

git stash pop
# all files listed in your commit as
# "new" will cause a conflict if they
# existed before. You can safely just
# use your file contents always.

git commit -m <Update locale message>
# Just use one commit for all changes
# in this case.
# You can use the stash commit to make
# a diff to your original changes. It
# should be empty if everything worked # out. `git diff stash` should show it.

git push --force-with-lease
```

Like that (committing the rename separately from all changes) the file will keep having one history across renames.

**Comment by Marak** [comment]
Thanks for your contributions @Moosh-be and @ohcibi 

Merged.

**Comment by Moosh-be** [comment]
oh cool

**Pull request merged**
