### PR TITLE
Allow user to specify separator to be used in mac address

### PR DESCRIPTION
**Pull request by paolo-tanium**
A mac address can be of the following forms:

```
000CF15698AD
00:0C:F1:56:98:AD
00-0C-F1-56-98-AD
```

In my use case, I need to use `-`. 

I would like to add a `sep` parameter to allow the user to specify the mac separator. It will default to using `:` if none is provided.

I can add tests to this pull request, but wanted to validate if this approach works for you before I spend too much time on it.

### CODE REVIEW

**Comment by paolo-tanium** [comment]
Any thoughts on this, @Marak ?

**Comment by Marak** [comment]
@paolo-tanium 

Seems like a good addition.

Can you add a test for this?

**Comment by paolo-tanium** [comment]
Added tests. Back for review.

**Comment by paolo-tanium** [comment]
@Marak Thoughts? I'd like to close this PR.

**Comment by Marak** [comment]
Looks good @paolo-tanium 

Merged.

Thank you for your contribution.

**Pull request merged**
