### PR TITLE
IBAN and BIC support

### PR DESCRIPTION
**Pull request by CoDEmanX**
IBANs are valid in length and checksum (3rd and 4th character), but bank codes are random and country-specific check values/sums are not taken into account.

BICs are formally okay, although designated as test BICs. Probabilities for 11 char BICs are arbitrary.

Also fixed spelling.

### CODE REVIEW

**Comment by Marak** [comment]
@CoDEmanX 

It looks like you ran the build script and included the results in your pull request.

Could you please open a new pull request which only contains the changes you've made?

Thank you.

**Comment by CoDEmanX** [comment]
How do you see that those results are included? Looks fine to me on GitHub (changes tab). There are so many changes because of the spell corrections.

**Comment by Marak** [comment]
@CoDEmanX 

I can't auto-merge any pull request which modifies the `/faker/build/` folder.

Please review your commits and you can see which files were included.

It looks like I may be able to `cherry-pick` just this single commit? https://github.com/CoDEmanX/faker.js/commit/1cbef3f0e95d884d03ba7194c68cac05ec7cd867

If that's the only relevant commit I should be able to pull it in.

**Comment by Leward** [comment]
Hello, any news on this PR? It's something I'd really like to have in the faker lib. 

Thank you.

**Comment by CoDEmanX** [comment]
I just forced-push an update. I manually removed build/* and examples/*, only the actually required changes should now be in the branch.

**Comment by CoDEmanX** [comment]
Yet another update: rebased against upstream master and resolved merge conflicts.

Possible TODO: rework iban.js to follow the module style of the rest of the files? The variables and functions defined there are not supposed to be called from outside however, they are just moved to a separate file instead of lined in finance.js, because there's a lot of static stuff and a couple helper functions, which aren't very useful outside the IBAN/BIC generation.

**Comment by tdekoning** [comment]
Why isnt this merged yet? I would love to use this feature.

**Comment by FaHeymann** [comment]
Bump, this feature would be nice.

**Comment by Marak** [comment]
I've just merged this.

Thank you for your contribution and also following up with a clean commit.

This will be included in the next release. Please let me know if you want to change anything before we ship.

**Pull request merged**
