### PR TITLE
Package faker for meteor.js

### PR DESCRIPTION
**Pull request by rbabayoff**
Hi,

I don't know if this is of interest to you, but meteor is rapidly becoming one of the most popular web application platforms (and github repos - # 11, at this point). I packaged faker for meteor, and instead of creating my own repo that will need to be updated every time a new faker version is out, I wanted to know if you (and other popular javascript library authors) would like to start supporting meteor out of the box. It is really not a lot of work. 2 tasks:

1. For every new version, update package.js (in the repo root) with the new faker npm version.

2. Everytime a new meteor version is updating it's node.js version dependency, update .travis.yml to have the meteor package tested on that node version.

For now, the meteor package will be published under my meteor's practicalmeteor org account, but you can publish it under your own instead. I can provide you the howto details.

### CODE REVIEW

**Comment by Marak** [comment]
@rbabayoff - I don't personally use Meteor, but this commit looks good.

Merged into `master` and is slated to be in the next release.

Thank you for your contribution!

**Comment by rbabayoff** [comment]
@Marak , need to update the node.js version meteor uses in tests. Also, since then, a new meteor community effort has been made to auto-publish packages to the meteor package server every time you tag a new version in github. See here:

https://autopublish.meteor.com/

Will you be interested in supporting this? It's really easy, and if yes, I'll run you through it quickly.

**Comment by Marak** [comment]
Sure.

**Comment by attio** [comment]
Hey guys, I was just hunting for a suitable Meteor package and wondering about the chance of getting autopublish going on the main repo. In the meantime, I plan to use the practicalmeteor:faker package but it would be amazing if we had autopublish on the main repo.

**Pull request merged**
