### PR TITLE
Update docs.md

### PR DESCRIPTION
**Pull request by toymachiner62**
Updated `faker.name.findName()` to `faker.name.firstName()`

### CODE REVIEW

**Comment by dmamills** [comment]
This change is incorrect, `faker.name.firstName()` returns a given name. Where as `faker.name.findName()` provides a given name and a surname, which the comment indicates.

**Comment by toymachiner62** [comment]
Ahh my bad. What comment indicates the difference?

**Comment by dmamills** [comment]
the line you edited shows a full name
`var randomName = faker.name.findName(); // Caitlyn Kerluke`

**Comment by toymachiner62** [comment]
Hmm doesn't seem very intuitive to me. I think it'd be better suited as `fullName` rather than `findName`

**Comment by tkoomzaaskz** [comment]
This PR considers updating an error in the docs. And @dmamills proved there is no error actually ;)

I agree that `fullName` sounds better than `findName`. But if we wanted to give better names for the generators, we need to consider backward compatibility for all those people who use faker.js. So if you still want to suggest new names, submit a new issue.

**Pull request closed without merging**
