### PR TITLE
[api] Added `internet.ipv6` method

### PR DESCRIPTION
**Pull request by cvega**
* Returns a random 8 octet ipv6 address

### CODE REVIEW

**Comment by Marak** [comment]
Looks good @cvega 

Merged.

Thank you for your contribution.

Also resolves #23

**Comment by jh86** [comment]
@Marak Sorry to bug, but how frequently do you cut npm-installable releases to npmjs.com? We're using this library in a test project and wondering if we should change version in our package.json to use a git/github URL.

Thanks!

**Comment by jh86** [comment]
@Marak Also, please let me know if I can help in any way getting a new version with this change uploaded to npm. Thanks again!

**Comment by Marak** [comment]
@jh86 -

I sent you an email in regards to release schedules.

If anyone is reading this message and wants to see more work on faker, please considering pledging to the project here: https://github.com/Marak/faker.js/issues/413

**Pull request merged**
