### PR TITLE
Add hy locale

### PR DESCRIPTION
**Pull request by raphaelhovsepyan**

### CODE REVIEW

**Comment by Marak** [comment]
Thank you for your contribution @raphaelhovsepyan 

I don't speak Armenian. Can anyone else who speaks Armenian review this PR for language accuracy?

If we can get a second native speaker to review I will merge.

Thanks again!

**Comment by raphaelhovsepyan** [comment]
> Thank you for your contribution @raphaelhovsepyan
> 
> I don't speak Armenian. Can anyone else who speaks Armenian review this PR for language accuracy?
> 
> If we can get a second native speaker to review I will merge.
> 
> Thanks again!

Thanks for response @Marak, I think it's hard to find a native Armenian reviewer in faker.js community. Anyway I copied all the words from wikipedia, so I don't thnik there is an accuracy issue.

**Comment by Marak** [comment]
Sounds good @raphaelhovsepyan 

Thanks again for your contributions!

Merged.

**Comment by Marak** [comment]
@raphaelhovsepyan -

Would you mind checking out this other PR? https://github.com/Marak/faker.js/pull/1039

Do we have duplicate data with `hy_AM`?

**Comment by raphaelhovsepyan** [comment]
> @raphaelhovsepyan -
> 
> Would you mind checking out this other PR? #1039
> 
> Do we have duplicate data with `hy_AM`?

Yes, this is the same locale.

**Pull request merged**
