### PR TITLE
[feature] internet: added userNameUnderscore/Dot/Hyphen

### PR DESCRIPTION
**Pull request by serv**
Added new internet methods

- `userNameUnderscore`
- `userNameDot `
- `userNameHyphen`

related to #171

### CODE REVIEW

**Comment by FotoVerite** [comment]
This seems like a good addition. I am slightly worried about the mound of methods we have going, slightly feeling that having a way to gsub spaces might make more sense then an individual method for each type.

**Comment by serv** [comment]
That's a valid concern. Can you give me an example of how the users would call the 3 cases?

Let me know if you agree with this.

- `userName('.')`
- `userName('-')`
- `userName('_')`

**Comment by snipesjr** [comment]
I feel like adding this would be a good addition, but would it be better to add it like this?


```
 userName: function (firstName, lastName, format) {
        var result;
        firstName = firstName || faker.name.firstName();
        lastName = lastName || faker.name.lastName();

        switch (format ? format : faker.random.number(5)) {
        case 0:
            result = firstName + faker.random.number(99);
            break;
        case 1:
            result = firstName + faker.random.array_element([".", "_"]) + lastName;
            break;
        case 2:
            result = firstName + faker.random.array_element([".", "_"]) + lastName + faker.random.number(99);
            break;
        //userName with dot separator
        case 3:
            result = firstName + "." + lastName;
            break;
        //userName with underscore separator
        case 4:
            result = firstName + "_" + lastName;
            break;
        //userName with hyphen separator
        case 5:
            result = firstName + "-" + lastName;
            break;   
        }
        result = result.replace(/'/g, "");
        result = result.replace(/ /g, "");
        return result;
    }
```

**Comment by FotoVerite** [comment]
serv yes that makes more sense or maybe UserNameFormated.

**Comment by serv** [comment]
Updated

**Comment by Marak** [comment]
Will not merge in current form.

Better to use a DSL and pattern matcher than using formats with arbitrary number values.

For example:

`userName('firstName.lastName')`

or

`userName('firstName-firstName--lastName')`

This seems related to https://github.com/Marak/faker.js/issues/199

Best to figure out a good system for mixins / custom formats that can be applied across the entire library.

**Pull request closed without merging**
