### PR TITLE
Issue #1101: Fixed 4 digit zips for eastern states.

### PR DESCRIPTION
**Pull request by wolfshirts**
Implemented this fix in address.js zipCodeByState function. Wrote tests.

### CODE REVIEW

**Comment by Marak** [comment]
@wolfshirts -

Thank you for your contribution.

We can't merge this PR in it's current form since it has a lot of changes that are linting related.

If you can update the PR to only include the actual functional changes being made we can get it merged.

**Comment by wolfshirts** [comment]
I'll fix it up and re-submit. Thanks!

**Comment by owens-ben** [comment]
@wolfshirts did you ever get a chance to fix this again

**Comment by wolfshirts** [comment]
I did resubmit, my solution used ES6. I could check this out this weekend.

**Pull request closed without merging**
