### PR TITLE
Change random image website from lorempixel.com to unsplash.com

### PR DESCRIPTION
**Pull request by chinclubi**
- Lorempixel's service usually down.
- Unsplash is more stable.
- Unsplash has more attractive images.
- The rest functions are still working, except randomize feature. (Random image category is working.)

### CODE REVIEW

**Comment by ekryski** [comment]
:shipit: This is so much better!

**Comment by ekryski** [comment]
@chinclubi would you be up for adding search too? It would be super rad if we can pass whatever string (it shouldn't have to be a defined category) and it just returns a random image from that search term. It would just be `https://source.unsplash.com/1600x900/?nature,water`.

**Comment by ekryski** [comment]
nevermind. Looks like your PR supports it but just passing `faker.image(1600, 800, 'random')` or `faker.image(1600, 800, 'city,fashion,')`

**Comment by chinclubi** [comment]
@ekryski Sorry for my late reply (so busy last week). 
I think current PR does not support for searching. I have to implement 'imageUrl' function too. 
I will check it this weekend 🐰 
Thx.

**Comment by ekryski** [comment]
@chinclubi no problem. I forked your fork. After working through it I realized it doesn't support searching. I might actually have time to implement it soon as well so keep me posted if you have time.

**Comment by chinclubi** [comment]
@ekryski sure! Anyway, I concern about "image" function. If we change "randomize" parameter type from boolean to string, the user who unfortunately update the module might have error(s) with the parameter. I have 2 solutions to solve this.
1. "randomize" parameter can be both boolean or string. If it is a string, program will search image from unsplash. .... I think, this is bad pattern and confusing :( but EASIER for developer. lol
2. Declare a new function(might be "imageSearch"), so leave "image" function as it be.
Do u have any suggestion?

**Comment by Marak** [comment]
@chinclubi 

Great idea!

Instead of dropping lorempixel entirely, we should make a graceful replacement with unsplash. 

I don't want to break or change any previous behaviors, I also would like the ability for multiple image providers / configurable providers.

Could you try to re-do this PR to not remove the lorem code paths and tests? I'll add unsplash as the default.

**Comment by chinclubi** [comment]
@Marak 

Please, check new commit. I try to create multiple image provider as you mentioned.

You can access Lorempixel or Unsplash function by using `faker.image.lorempixel` or `faker.image.unsplash`. 

I've no idea how to make a good pattern for setting default as Unsplash. Should it be `faker.image.xxx` or `faker.image.default.xxx` which xxx is an property of Unsplash object ???



@ekryski 

[https://github.com/chinclubi/faker.js/blob/900f3d87cbfd9b86119c4505e3b9dc1e84ea5969/lib/image_providers/unsplash.js#L20](url)

Check this file. I already implement a searching method in Unsplash.js.

**Comment by Marak** [comment]
Thanks @chinclubi 

I'll see if I can put a good pattern in and get this merged for next release.

**Comment by AO16** [comment]
:+1:

**Comment by gbl3** [comment]
Guys, any update on the faker.image stuff? I was trying to use it but lorempixel is really slow, so this function is becoming useless sometimes, I'm having to use avatar instead of image, but it's not the same result.

**Comment by romandragan** [comment]
@Marak 

Any updates regarding approving this PR? Cause as mentioned in #364 Lorempixel.com is responding at crawling speeds now, that makes whole `image` function totally useless.

**Comment by townmulti** [comment]
+1

**Comment by BBBmonkey** [comment]
+1

**Comment by armadillojim** [comment]
FWIW, the folks over at #641 had some ideas for additional image services.

**Comment by Marak** [comment]
We'll have to get this fixed for the next release `v5`.

This PR is a good start. If anyone else can review or make suggestions it would help.

**Comment by Marak** [comment]
If anyone has additional input on this PR or issue #641 please let us know.

We'll be resolving this soon.

**Comment by mouafa** [comment]
lorempixel became unreliable, personally speaking, when I use faker to generate an image URL I expect to get the image when i request the given URL since I mostly use that URL in a UI prototype, it doesn't look good that the image is not displayed.

@Marak is there anything we could do to move this further?

**Comment by Marak** [comment]
Merged.

This will require a bit more work before it's ready for release in order to establish the API for default provider and switching providers.

If anyone has any additional optional providers they would like to add besides `lorempixel` and `unsplash`, please let us know.

**Comment by pixelbacon** [comment]
[](https://picsum.photos/)

Wonderfully high uptime, uses unsplash as the source.

**Pull request merged**
