### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Ci shake :cocktail: with coverage, and new travis :)

### CODE REVIEW

**Comment by Marak** [comment]
@AdrieanKhisbe 

This seems good.

Unfortunately commit "Improved ci" is cause continuous integration tests to fail.

Would you mind investigating why this test is now fail? https://travis-ci.org/Marak/faker.js/jobs/99261946

It would help me to be able to merge pull request without having to make modification.

Thank you for your contribution!

**Comment by Marak** [comment]
Error in Travis might not be related to your changes...not sure.

**Comment by AdrieanKhisbe** [comment]
@Marak 
The bug is only for latest node version, to specific 0.10.29. ;)
cf https://travis-ci.org/Marak/faker.js/jobs/99261946

      The command "if [ "$(node -v)" = "v0.10.29" ]; then spacejam test-packages --mongo-url=dummy ./; fi" exited with 8

**Comment by Marak** [comment]
Closing due to inactivity.

I've added `nyc` and some badges for coverages.

Please feel free to re-open.

**Pull request closed without merging**
