### PR TITLE
Add name locale vi

### PR DESCRIPTION
**Pull request by zzNuAzz**

### CODE REVIEW

**Review by ohcibi — CHANGES_REQUESTED** [review]
Is the list of first name the concatenation of female and male first name? If yes you could concatenate them programmatically by requiring both female and male first name and assign `female_names.concat(male_names)` to the `exports` object.

**Comment by zzNuAzz** [comment]
> Is the list of first name the concatenation of female and male first name? If yes you could concatenate them programmatically by requiring both female and male first name and assign `female_names.concat(male_names)` to the `exports` object.

Thanks, I've changed it already.

**Comment by ohcibi** [comment]
Thanks. @Marak lgtm

**Comment by Marak** [comment]
Thank you for your contributions @zzNuAzz

Thank you for the review @ohcibi 

Merged!

**Pull request merged**
