### PR TITLE
Add support for en_GH locale

### PR DESCRIPTION
**Pull request by prinx**
While testing I ran the the `browser` script, which overwrote the files in the `examples` and `dist` folders.

### CODE REVIEW

**Comment by Marak** [comment]
We can't accept pull requests that modify `/dist` or `examples`

**Comment by prinx** [comment]
Yes, I was wondering. Thanks. will revert the changes and create a PR

**Comment by prinx** [comment]
Hi @Marak . FYI.

**Comment by Marak** [comment]
Thank you for your contributions @prinx 

Merged!

**Comment by prinx** [comment]
You are welcome @Marak . Thanks for merging too. Hoping to contribute more.

**Pull request merged**
