### PR TITLE
Create female/male_first_name.json in pl locale

### PR DESCRIPTION
**Pull request by MoonWalker0**
Extracted male names from first_name.json in pl locale.
Hoping for faker to assign male name to male gender (as it is right now e.g. in en locale).

### CODE REVIEW

**Comment by Marak** [comment]
@MoonWalker0 -

Thank you for your contributions.

Can you combine this and your other Pull Request into a single Pull Request?

In addition, can you remove the now duplicated `first_name` data by replacing it with an `Array.concat`? An example of this pattern can be found here: https://github.com/Marak/faker.js/blob/master/lib/locales/fr/name/first_name.js

**Comment by MoonWalker0** [comment]
@Marak 
Thank you.
Updated as suggested.

**Comment by Marak** [comment]
@MoonWalker0 -

Tests are now failing. Looks like a typo.

**Comment by MoonWalker0** [comment]
@Marak
Sorry for that mess. Tests are passing now.

**Comment by MoonWalker0** [comment]
Sorry for the reopening - it was by mistake.
I wanted to ask - how often do you merge PRs?

**Comment by Marak** [comment]
Thank you for your contributions @MoonWalker0 

Merged.

Please let us know if you find any other ways we can improve the `pl` locale.

**Pull request merged**
