### PR TITLE
Croatian locale + lib locale folder added

### PR DESCRIPTION
**Pull request by TomislavStrugacevac**

### CODE REVIEW

**Comment by Marak** [comment]
@TomislavStrugacevac -

Thank you for your contribution.

We cannot merge this in it's current form due to duplicate data such as `lorem` and `company` modules.

Please only include unique data specific to the `hr` locality. All other common data will use faker's fallback mechanism.

**Comment by TomislavStrugacevac** [comment]
> @TomislavStrugacevac -
> 
> Thank you for your contribution.
> 
> We cannot merge this in it's current form due to duplicate data such as `lorem` and `company` modules.
> 
> Please only include unique data specific to the `hr` locality. All other common data will use faker's fallback mechanism.

Done

**Comment by Marak** [comment]
@TomislavStrugacevac - 

I still see a `time_zone.js` in there? I also saw a couple of issues with empty spaced lines. 

Can you please double check everything. We really don't want to merge duplicate data.

Thanks.

**Comment by TomislavStrugacevac** [comment]
Should be ok now, removed duplicates and empty lines and added more translations.

**Comment by Marak** [comment]
@TomislavStrugacevac -

This is looking good.

Will be merged soon.

**Comment by TomislavStrugacevac** [comment]
Cool thank you for the help :)

**Comment by TomislavStrugacevac** [comment]
@Marak any news on this one?

**Pull request merged**
