### PR TITLE
Add Ethereum Address

### PR DESCRIPTION
**Pull request by ygnr**
Added functions to generate random hexadecimal string and ethereum address.

### CODE REVIEW

**Comment by ygnr** [comment]
@Marak Can you please review and merge this.

**Comment by Marak** [comment]
Duplicate https://github.com/Marak/faker.js/pull/395

@ygnr - Please review other issue and let me know if there is overlap.

**Comment by ygnr** [comment]
@Marak Yeah, looks like both PR's are similar in functionality. I guess I have addressed the comments of #395 as well in this PR.

**Comment by Marak** [comment]
Looks good @ygnr 

Merged.

Thank you for your contribution.

**Pull request merged**
