### PR TITLE
Translate to ar

### PR DESCRIPTION
**Pull request by anas-qa**
Change scope over `lib/locales/ar`

- Translate EN strings under `lib/locales/ar/address/country.js`
- Add more AR related strings under `lib/locales/ar/address/secondary_address.js`
- Add more AR related strings and remove duplications under `lib/locales/ar/commerce/color.js`
- Translate EN strings under `lib/locales/ar/commerce/department.js`
- Create a new commerce file `lib/locales/ar/commerce/product_name.js`
- Create a new dir `lib/locales/ar/team`
- Create a new dir `lib/locales/ar/vehicle`

### CODE REVIEW

**Comment by anas-qa** [comment]
@marak it would be appreciated if you can review/merge this PR alongside with [726](https://github.com/Marak/faker.js/pull/726) as it's adding `lib/locales/ar/name` _DIR_

**Comment by Marak** [comment]
@anas-qa 

شكرا لمساهمتك. هل يمكن لشخص آخر أن يراجع هذا للتأكد من دقته؟ أنا لا أتحدث العربية.

Thank you for your contribution. Would it be possible to have another person review this for accuracy? I can't really read Arabic and will run this PR through the translator. Would prefer to have another human review it as well.

Thanks again!

**Comment by anas-qa** [comment]
@Marak Thank you for your reply.

I am a native Arabic speaker and I can confirm that the provided Arabic strings are correct and SFW (safe for work).

However, I'll ask someone to review

**Comment by Marak** [comment]
Thank you for the additional review @thaerlabs 

I will trust in @anas-qa and @thaerlabs that these changes to `ar` locality are accurate.

Merged. عمل عظيم. نجاح كبير.

**Pull request merged**
