### PR TITLE
Add link to 4.1.0 readme

### PR DESCRIPTION
**Pull request by WillGibson**
Because I keep getting confused when I go to https://github.com/Marak/faker.js to look up the API methods, and I'm sure i'm not alone.

### CODE REVIEW

**Comment by RichardLitt** [comment]
This looks good to me. What is needed for the 5.0.0 release to be the official release?

**Comment by RichardLitt** [comment]
Sorry. See #692

**Comment by WillGibson** [comment]
Hmmm, that last bit of https://github.com/Marak/faker.js/issues/692 is a bit confusing. Faker.js is great, 100%, I use it nearly every day and I'm doing my $5/month to support it, but I saw @jonrimmer's comment before it was deleted and it was perfectly reasonable, including him saying "I would be happy to contribute", which is a positive way to start an exchange. @Marak I feel torn now, I want to contribute to Faker.js with my time and money, it's a superb tool, but your response to @jonrimmer seemed a bit harsh. What's up?

**Comment by Marak** [comment]
`ReadMe.md` is autogenerated. Please see project structure.

**Pull request closed without merging**
