### PR TITLE
Added faker.random.semver.

### PR DESCRIPTION
**Pull request by JustinMcConnell**
Added faker.random.semver.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
:+1: :)

**Comment by Marak** [comment]
Seems harmless enough.

Thank you @JustinMcConnell 

Unfortunately, I can't auto-merge this because you modified the auto-generated documentation.

Will merge later.

**Comment by JustinMcConnell** [comment]
Would it help if I removed the documentation changes from the PR?

**Comment by AdrieanKhisbe** [comment]
@JustinMcConnell, would be better to revert 3df1487. 
(do a `git reset --hard 3df1487`)

**Comment by Marak** [comment]
Merged.

I ended up moving `semver` method to new `System` module since it seemed somewhat related.

We should try to keep the amount of methods in `faker.random` to a minimum.

**Comment by JustinMcConnell** [comment]
How do I use this?  I have the latest version (3.0.1)

> var faker = require('faker')
> faker.system
undefined

**Comment by Marak** [comment]
@JustinMcConnell -

We still have published a new release yet. You'd have to clone the master branch of Github.

Should have a release soon.

**Pull request closed without merging**
