### PR TITLE
Add address for fa locale

### PR DESCRIPTION
**Pull request by Aleyasen**

### CODE REVIEW

**Comment by Marak** [comment]
This is good @Aleyasen, thank you!

Would it be possible to expand on this PR with more data like first and last names? It would help a lot.

Merged.

**Comment by Aleyasen** [comment]
Thanks @Marak to approve the PR. 
It's a good idea, I'll expand the first and last names soon.

**Comment by Aleyasen** [comment]
Please let me know if you any other idea for expanding it.

**Comment by Marak** [comment]
I think first and last name is a good start. Not sure what else to add at this moment.

You could look at some of the other localities for inspiration.

**Pull request merged**
