### PR TITLE
Add internet.url()

### PR DESCRIPTION
**Pull request by dmamills**
As requested in #162

### CODE REVIEW

**Comment by decal** [comment]
@Marak It would be *leet* if you added a `tuple`/`triple` or even a small `array` of some typical forgot password questions and associated answers that (hypothetically) have `true` correspondence to the rest of the fake person.  Existential logic propositions __could__ be used for proving factuality.  Regardless, I'd still be thrilled by a simple randomly generated data structure containing forgot password question and answer `string` data!    
- - -

**Comment by nunofgs** [comment]
@decal was your comment meant for this PR?

**Comment by nunofgs** [comment]
LGTM.

@Marak I would love to get this PR merged. Can you take a look at it?

**Comment by Marak** [comment]
Looks good, thanks!

**Pull request merged**
