### PR TITLE
Create a method to genarate a string using mask, like jquery mask

### PR DESCRIPTION
**Pull request by norato**
It's useful for creating values like Brazilian CPF and other things

### CODE REVIEW

**Comment by Marak** [comment]
@norato 

This looks good.

Could you quickly elaborate on how this is different from these existing methods:

`helpers.replaceSymbolWithNumber`
https://github.com/Marak/faker.js/blob/master/lib/helpers.js#L36

`helpers.replaceSymbols`
https://github.com/Marak/faker.js/blob/master/lib/helpers.js#L18

I think we might have some overlap? My goal is to provide the best API method for faker, so I'd like to understand exactly which functionality we have, and what we are adding. The existing helper methods seem like they could be refactored / replaced.

**Comment by chilicoder** [comment]
@Marak this will cover the case, I have now
when you need digit OR char on some place

But looks like its just better to add `*` case to `replaceSymbols`.

**Comment by chilicoder** [comment]
I put a PR

**Comment by Marak** [comment]
Closing.

Merge with #524 

I think that will cover the functionality requested in this PR as well.

**Pull request closed without merging**
