### PR TITLE
Highlight code syntax in readme

### PR DESCRIPTION
**Pull request by xamgore**

### CODE REVIEW

**Comment by Marak** [comment]
All changes to the documentation must  be done in `./build/src/docs.md`

**Comment by xamgore** [comment]
@Marak well, but this PR fixes code highlighting on the [main repository page](https://github.com/Marak/faker.js#usage).

**Comment by Marak** [comment]
Yes, and then it would be overwritten and lost immediately after a new build.

**Comment by Marak** [comment]
Please see: https://github.com/Marak/faker.js/blob/master/CONTRIBUTING.md

**Comment by xamgore** [comment]
Got it, thanks.

**Pull request closed without merging**
