### PR TITLE
Normalize locales

### PR DESCRIPTION
**Pull request by Moosh-be**
Just finish the work of #915 opened on May 31 by oscarmarcelo

### CODE REVIEW

**Comment by Moosh-be** [comment]
hum, Strange, that work localy

**Comment by Moosh-be** [comment]
Yep. @oscarmarcelo , @Marak the travis  is green !

**Comment by Moosh-be** [comment]
Yep. @oscarmarcelo , @Marak the travis  is green !

**Comment by Marak** [comment]
@Moosh-be -

Thank you for your contributions.

It looks like we have two separate units of work here with @oscarmarcelo, but also everything looks OK

Merged!

**Comment by Moosh-be** [comment]
@Marak, yes I'm sorry  I just finish  the great work of @oscarmarcelo . But I just Don't found how to continue  his  branch , so I made a new fork and new PR.

**Pull request merged**
