### PR TITLE
Add Georgian locale

### PR DESCRIPTION
**Pull request by Stichoza**
### Tests

:white_check_mark: All tests passed successfully

### Gulp

I have not built the project. Actually I run the `gulp` task, but I haven't included that commit in this pull request. I think it would be better if you build it yourself, because gulp task changes more than I think it should. Like this one:

screen shot 2015-01-18 at 06 01 23

### Added data

 - title
 - separator
 - name
  - first_name
  - last_name
  - prefix
  - title
    - descriptor
    - level
    - job
  - name
 - address
  - city_prefix
  - city_suffix
  - country
  - building_number
  - street_prefix
  - secondary_address
  - postcode
  - city_name
  - city
  - street_title
  - street_name
  - street_address
  - default_country
 - company
  - prefix
  - suffix
  - name
 - internet
  - free_email
  - domain_suffix
 - phone_number
 - cell_phone

### CODE REVIEW

**Comment by Stichoza** [comment]
Tested `faker.min.js` in Google Chrome DevTools after `gulp` task and it works perfectly. And still I don't commit built files for reasons stated above.

screen shot 2015-01-18 at 06 50 35

**Comment by safareli** [comment]
+1

**Comment by tatocaster** [comment]
+1

**Comment by Stichoza** [comment]
Thanks guys, but please avoid bare "+1" comments.

**Comment by tkoomzaaskz** [comment]
@Stichoza thank you for awesome contribution! And sorry it took us so long to answer you. Anyway, we'd like to include your contribution in upcoming release, just as fe other locale packages. Could you please make sure it is in sync with current `master` branch (i.e. resolve conflicts in a new commit, if there are any)?

@safareli @tatocaster have you checked above commits? Unfortunately, I'm, unable to judge it myself anyhow...

**Comment by Marak** [comment]
@tkoomzaaskz -

In these cases it might be better / faster for you to just do the sync / merge yourself as a project maintainer.

**Comment by safareli** [comment]
@tkoomzaaskz  yes everything is perfect :3

**Comment by Stichoza** [comment]
Added more names.

**Comment by Marak** [comment]
Looks good, thanks!

**Comment by Stichoza** [comment]
Thank you too!

**Pull request merged**
