### PR TITLE
Hacker phrase module

### PR DESCRIPTION
**Pull request by dhilt**
What has been done:

 - hacker phrase array has been extracted into a separate module (en-locale)
 - hacker phrase module has been added for ru-locale
 - hacker ru-locale translations have been updated to completely satisfy ru-locale phrase templates
 - hacker ru-locale abbreviation module has been added

A very silmple refactoring... As a first step, I guess, this would be enough to give an ability of phrase templates customization to the translators!

### CODE REVIEW

**Comment by 770580** [comment]
I need this feature much!

**Comment by Marak** [comment]
This looks good! Let's get it merged.

**Comment by dhilt** [comment]
@Marak Good news!

**Comment by Marak** [comment]
Merged.

Thank you!

**Pull request closed without merging**
