### PR TITLE
feature/lorem_word

### PR DESCRIPTION
**Pull request by lykmapipo**
Extend `faker.lorem` with ability to generate a `single word`

[See issues#275](https://github.com/Marak/faker.js/issues/275)

### CODE REVIEW

**Comment by Marak** [comment]
@lykmapipo 

Could you please re-open the pull request with only the necessary modifications?

You've made changes to files and places you should not have. ( Do not remove spacing from functions )

**Comment by jalcine** [comment]
@lykmapipo For a tip, you can unstage these changes and use `git commit --interactive` to _only_ stage the changes that relate to this issue!

**Comment by Marak** [comment]
Also, documentation will auto-generate on release, so don't worry about changing that.

**Comment by lykmapipo** [comment]
@Marak 

My bad. Can you atleast add [jshint](https://github.com/jshint/jshint) into this project. It will help us to adhere to code style required.

**Comment by Marak** [comment]
You don't need a jshint file to know not to modify things randomly.

https://github.com/Marak/faker.js/blob/master/.jshintrc

**Comment by Marak** [comment]
Or if you don't bother looking for it....

**Comment by lykmapipo** [comment]
@Marak 

Ok

**Pull request closed without merging**
