### PR TITLE
Added npm badge with version [badge.fury]

### PR DESCRIPTION
**Pull request by troy0820**
Added npm version badge on README.md

### CODE REVIEW

**Comment by tkoomzaaskz** [comment]
@troy0820 could you please add your line to [build/src/docs.md](build/src/docs.md) and then run `gulp` (see [build](build))? The docs are generated from the sources and the badge need to get there in first place.

**Comment by troy0820** [comment]
Got it. Nice work by the way.

**Comment by troy0820** [comment]
Sorry almost forgot to commit the Readme.md changes.

**Comment by tkoomzaaskz** [comment]
@troy0820 Thank you, trying to do my best :) keep your thumbs up for the upcoming release. I want to include your badge there.

**Comment by tkoomzaaskz** [comment]
@troy0820 I couldn't find your username in github's cross-fork pull request system, don't know why. And I want to include no source changes in upcoming releases, so I just made a subset of your changes. Hope you're ok with it. Hopefully we'll improve the workflow with faker and it'll be easier to create and merge PRs.

**Comment by troy0820** [comment]
I'm okay with it.  If the changes couldn't automatically be merged you could've used my remote branch as a local subset of your repo and merged the changes to whatever branch you wanted.  As long as the changes get made, I'm fine with it.

**Comment by tkoomzaaskz** [comment]
I'm not happy with not merging your commit, really. But I want to use the cross-fork PR system that github supports, it is really nice for choosing a set of commits to create a temporary release branch. There is a fork-select widget and I've got no idea why, but `troy0820` was not available there and I couldn't merge it... Hope to merge your changes next time.

**Comment by Marak** [comment]
@tkoomzaaskz -

You'll want to add other developers forks as remote branches on your local git setup.

From here, you can fetch the remote branch, then `cherry-pick` commits into your working branch.

If you aren't familiar with the process  of cherry-picking I'd recommend doing a bit of research. It's pretty easy.

**Comment by Marak** [comment]
Seems to be merged. Thanks!

**Pull request closed without merging**
