### PR TITLE
New feature/fix - Image providers

### PR DESCRIPTION
**Pull request by chffUA**
Includes:

- New image provider - https://www.thispersondoesnotexist.com/

- Switch between **Lorempixel**, **Unsplash** and **This Person Does Not Exist** as image providers with `faker.image.setProvider`

- Unsplash as the default image provider

-----

**Issues**

Fixes [#755](https://github.com/Marak/faker.js/issues/755)
Fixes [#679](https://github.com/Marak/faker.js/issues/679)

-----

**Example**

### CODE REVIEW

**Comment by tripu** [comment]
@Marak, this looks good. Are you on it?

**Comment by Marak** [comment]
@chffUA @tripu 

This looks good to me, but we have a couple conflicts now with another image provider we added.

If you can please resolve these conflicts I will hit the merge button.

Thank you!

**Comment by tripu** [comment]
:mega:  
**Anyone interested in this particular feature (and in ongoing development of Faker in general)**:  
this is now part of my own fork.

* GitHub project: [`tripu/faker.js`](https://github.com/tripu/faker.js)
* Alternative npm package: [`phaker`](https://www.npmjs.com/package/phaker)

**Comment by tripu** [comment]
@chffUA, given recent developments (#1046), I suggest we close this PR&hellip;

**Comment by alexellis** [comment]
You should probably change `https://github.com/tripu/faker.js` to `https://github.com/tripu/phaker` as it's not really the done thing to fork an OSS project (using its trademark) and then to give it the same name.

**Comment by Marak** [comment]
Advertising of other projects is not allowed, sorry. 

Comments have been deleted.

Thread is now locked.

**Pull request closed without merging**
