### PR TITLE
Possible solution for uifaces.com cancelled

### PR DESCRIPTION
**Pull request by caiotarifa**
https://uifaces.com

### CODE REVIEW

**Comment by MrToto54** [comment]
We can find an alternative of https://uifaces.com at https://uifaces.co/
It can be interesting to use it.

**Comment by caiotarifa** [comment]
@MrToto54 Working with UiFaces.com needs external API access. RandomUser.me allows you to use the current architecture, which will cause less compatibility problems

**Review by crismarucci — APPROVED** [review]

**Comment by crismarucci** [comment]
Still not working cause of uifaces.com cancellation, I think that this solution is ready to go.

**Comment by Marak** [comment]
This has already been resolved in `master` and the latest published version.

Please feel free to update to the latest and see if avatars are working.

Cheers.

**Pull request closed without merging**
