### PR TITLE
Greek locale translation

### PR DESCRIPTION
**Pull request by kbariotis**
This is the Greek translation as requested at #246.

(@Marak wow lot of noise in the PR)

### CODE REVIEW

**Comment by Marak** [comment]
@kbariotis -

Would it be possible to open a new pull request without the build and example files?

As per #237 we've got to reduce noise / size of the git repo.

The idea is to do one build per release. Thanks!

**Comment by kbariotis** [comment]
@Marak better?

**Comment by Marak** [comment]
@kbariotis -

Looks pretty good!

It looks like you've duplicated some data ( such as `internet` and `lorem` ). Is there a reason for this?

**Comment by kbariotis** [comment]
@Marak I believe that those two are globally accepted as is, so I didn't have to translate them. Also, since there is no fallback to another language, it's better to have them than not have them. What you think?

**Comment by Marak** [comment]
@kbariotis - I merged extra data for now. Until I can make a solution upstream for better fallbacks, this is a good solution you made. 

Thank you for your contribution!

**Comment by bchavez** [comment]
I think the Greek locale isn't complete yet... seems like it's missing an entry in: https://github.com/Marak/faker.js/blob/master/lib/locales.js

**Pull request merged**
