### PR TITLE
add chinese lorem and update chinese phone format

### PR DESCRIPTION
**Pull request by lonso**

### CODE REVIEW

**Comment by HaroldPutman** [comment]
yes, please!

**Comment by Marak** [comment]
This seems like a nice addition.

Can anyone confirm that the Chinese lorem text doesn't contain anything offensive and or phrases that might get us tagged by the great firewall? @HaroldPutman ?

Putting the text through google translate was showing some strange words...but nothing too bad? I'm not sure. Don't want to cause any issues.

**Comment by Marak** [comment]
Translation:

```js
module [ "exports"] = [
  'Abba', 'Achang', 'A big,' 'Adi', 'fools', 'hooligan', 'Afu', 'princes', 'donkey', 'Liza', 'Allah' 'Ali', 'Mom,' 'Oman', 'Mei', 'Niang'
  'Lady', 'Auntie', 'flattery', 'Egypt', 'suffer side', 'one by one', 'beaten', 'wait until', 'hungry', 'one by one', 'survive', ' suffer shoulder, '' near to ',' scolded '' Punished ',' next '
  'Beating', 'Damn,' 'Oh,' 'cancer', 'cancer', 'cancer', 'Airan', 'Wormwood', 'Fitch', 'Ai Peng', 'moxa', ' Artemisia ',' be too embarrassed to mention ',' find it difficult to ',' in the way ',' eyesore '
  'Due', 'pet name', 'love', 'love', 'caress',' patriotism ',' loving ',' love ',' love ',' lovingly ',' love ',' Amy ',' loving ',' love ',' daughter ',' wife '
  'Love', 'love', 'love that', 'hear', 'care', 'small love', 'love', 'love and hate', 're-love', 'love child', 'Pass' 'horse', 'saddle', 'amino' 'ammonia', 'ammonia'
  'Placement', 'Anderson', 'Andhra', 'stable', 'settled', 'placed', 'law-abiding', 'appease', 'well', 'Anhui', 'settle down', 'quiet' 'home', 'well-being', 'peace', 'Amman'
  'Sleep', 'Min', 'peace', 'arrangement', 'amp', 'Anqing', 'security', 'safe', 'placement', 'install', 'shelter', 'nerves' 'quiet', 'comfortable', 'sleep', 'Aetna'
  'Diem', 'clofibrate', 'safety', 'comfort', 'stable', 'rest in peace', 'carefree', 'serene', 'quiet', 'resting', 'peace of mind', 'comfortable' 'camp', 'buried', 'peace of', 'placement'
  'Installation', 'peaceful', 'ampoules'' according to insert ',' Click ',' press', 'key', 'mortgage', 'reasonably', 'Example', 'quantity', ' press the '' ring the bell ',' feeling the pulse ',' massage ',' annual '
  'Button', 'arrange', 'schedule', 'daily', 'time', 'supposedly' 'press',' depressed ',' note ',' month ',' in accordance with ',' press set ',' hold down ',' secret ',' bunker ',' dark cabin '
  'Hidden', 'dark', 'dull', 'underground passage', 'darkroom', 'stab in the back', 'implied', 'signal', 'cassette', 'dark', 'floral', 'unmentionable disease' 'markings' 'reef', 'covertly', 'undercurrent'
  'Ambiguous',' secret door ',' to myself, '' the dark disk ',' hidden weapon ',' dim ',' assassination ',' invisible injury ',' Shao ',' hinted '' dark matter ',' darkroom '' plot ',' spy ',' feel pleased, '' cartridges'
  'Under the dark', 'dark line', 'black box', 'dowel', 'code word' 'metaphor', 'secret', 'secretly', 'dark *', 'shore', 'lighthouse', 'shore '' chopping board ',' crime ',' criminals', 'cases'
  'Files',' case ',' the case ',' desk ',' case ',' dirty ',' high-spirited ',' euphoric ',' expensive ',' proudly ',' head ',' high-spirited ',' full ',' oz ',' obo ',' coming '
  'Survive', 'torture', 'boil mill', 'boil heart', 'Aoyao', 'stay up', 'porridge', 'fly', 'Audi', 'mystery', 'secret', ' Alto ',' anti-Australian ',' Australian wool ',' Macau '
  'Complain', 'hold', 'hold', 'report', 'Report', 'compensation', 'was reported,' 'pay', 'revenge', 'quote', 'reward', 'declaration '' report '' report ',' newspapers', 'debt of gratitude'
  'Scrap', 'revenge', 'Report', 'declaration', 'newspaper', 'serve the country', 'quote', 'report a success,' 'the press',' alarm ',' newspapers', 'sit', ' reported ',' registration ',' announcer ',' approval '
  'Submitted', 'journalist', 'obituary notice,' 'the newspaper', 'newspaper', 'reported the trial,' 'reported missing', 'timekeeping', 'countin', 'submit', 'kiosks',' newsboys', 'header', 'Treasury', 'good news',' newspaper boxes'
  'Reimbursement', 'crowing', 'serve', 'messenger', 'repair', 'newspaper', 'responded with,' 'retribution', 'newspapers', 'reimbursement', 'newspapers', 'sudden illness' 'crash', 'riot', 'outbreak', 'Storm'
  'Exposure', 'flash flood', 'tyrant', 'violence Library', 'profiteering', 'violence', 'violent', 'exposure', 'the rate of violence', 'riot', 'mob', 'rage' 'oppressive', 'exposure', 'violence dead', 'violent income'
  'Rampage', 'violent conflict', 'thugs',' violence ',' rain ',' violent ',' boom ',' tyranny ',' violent ',' ocelot ',' leopard ',' cup ',' cup ',' cup ',' tablets', 'stone',
  'Beilin,' 'inscriptions',' rubbings', 'Beituo' 'inscription', 'Monumental', 'Beizuo', 'stele', 'sad', 'tragic', 'sad', 'Mourning Becomes Electra', ' anger ',' Elegy ',' pessimistic ',' wail '
  'Tragedy', 'misery', 'sad', 'grief', 'plaintive', 'weeping', 'sadness',' sad ',' sad ',' lament ',' sad ',' sad woo '' sadness', 'sad pharynx', 'Iceland', 'Ice'
  'Nose', 'nose', 'nasal', 'stuffy', 'feeding', 'feel sad,' 'nose', 'nose', 'breath', 'rhinitis',' twang ',' nose ',' originator ',' sinus', 'BB', 'example',
  'Score', 'gestures', 'and than', 'Search', 'shoulder to shoulder', 'more', 'proportion,' 'infer', 'next', 'ratio', 'Bimei', 'match' 'than you,' 'than with' 'than' 'heat'
  'For example,' 'race', 'Bissau', 'a test', 'peso' 'than him,' 'than her,' 'than I am,' 'contest', 'fly', 'analogy', 'cf. '' ratio ',' share ',' all over ',' than with '
  'Compared to', 'scorn', 'vulgar said,' 'my humble opinion', 'shallow', 'disdain', 'I', 'contempt', 'vulgar', 'Biyi', 'stroke', 'A pen' , 'style', 'pen', 'strokes', 'stroke'
  'Pen', 'pen', 'pen for', 'stroke', 'stroke', 'Pen', 'handwriting', 'Notes', 'carriage', 'pen stand,' 'strokes', 'Notes' 'pen name', 'ink', 'gesture', 'written'
  'Pen by', 'stroke', 'written calculation', 'sketches and notes,' 'pen', 'pen', 'trim', 'Pen', 'written', 'clerical error', 'pen', 'refill' 'pencil', 'translation', 'I', 'straight'
  'Brushstrokes', 'the other side', 'another', 'blue', 'blue sky', 'blue', 'green', 'Jasper', 'Castor', 'unblinded', 'After all,' 'reveals' 'life', 'graduate', 'killed', 'currency'
  'Currency', 'asylum', 'blessing', 'arthralgia', 'closed', 'closing', 'closed', 'closed', 'behind closed doors',' closing ',' breath ',' closed ',' closed ',' eyes closed ',' shut up, '' rumor '
  'Closet', 'Wall', 'gecko', 'murals', 'barriers', 'Bili', 'Fireplace', 'wall', 'wallpaper', 'wall clock', 'arm', 'arm' 'arm', 'arm', 'armband', 'shelter'
  'Dark', 'taboo', 'evasive', 'away', 'avoid', 'refuge', 'avoid', 'summer', 'above suspicion', 'evil', 'rain', 'contraception' 'Your Majesty,' 'spur', 'whipping', 'flagella'
  'Fireworks', 'whips', 'whip', 'whip flat basket tray', 'Shoreline', 'border town' 'border' 'winger', 'margins', 'border', 'marginal', 'frontier' 'corner', 'border', 'border', 'border checkpoint'
  'SIDE', 'border', 'wing', 'border', 'wicket', 'border', 'border', 'frontier', 'skirt', 'sideline', 'edge', 'edge' 'remote', 'Reaches the border', 'border', 'denounce'
  'Derogatory term,' 'demeaning', 'Demotion' 'derogatory' 'derogatory' 'derogatory responsibility', 'devaluation', 'cypress', 'pole', 'lentils', 'almond', 'flat iron' , 'flat', 'oblate', 'flat word,' 'all over'
  'Everywhere', 'over', 'everywhere', 'flaunt' 'specimen', 'model', 'scale', 'marked', 'subject', 'base price', 'punctuation', 'calibration', ' Lot ',' benchmarking ',' elevation ',' label '
  'Marker', 'price', 'scalar', 'marked', 'Signs',' tag ',' javelin ',' identity ',' marked ',' tender ',' title ',' plotting '' under standard ',' marked ',' slogan ',' flag '
  'Confession', 'statistical forms',' surface ',' rear sight ',' expression ',' Band ',' cousin ',' table covers', 'cousin', 'table', 'table work', ' regardless table ',' token ',' cousin ',' vote ',' we '
  'Case', 'bracelet', 'show', 'model', 'cousin', 'surface', 'show', 'dial', 'skin', 'cousin', 'face', 'cousins' 'means' 'statement' 'topsoil', 'performance'
  'Entry', 'representation', 'topography', 'cousin', 'performance', 'recognition', 'recognition', 'hands',' nephew ',' Do not be, '' aka '' elsewhere ',' other ',' do not move, '' do not give ',' do not worry '
  'Other countries', 'alias', 'do not worry', 'other home', 'unique', 'Do not look,' 'Buick', 'do not cry', 'Do not come,' 'leave' 'Another View' 'alias', 'do not read', 'awkward', 'do not go', 'others'
  'Do not be,' 'Villa', 'never mind', 'different kind', 'do not have', 'pin', 'unique', 'not words', 'do not go', 'Do not mouth', 'flat valley' 'bum', 'deflated crumbs' 'on the verge' 'endangered' 'on the brink'
  'Marina', 'Riverside', 'hotel', 'guests', 'guests', 'object', 'two sides', 'reject', 'get rid of', 'abandon', 'mutiny', 'soldiers' 'Art of War', 'broken down into smaller,' 'military', 'warship'
];
```

**Comment by HaroldPutman** [comment]
Sorry I don't read/speak Chinese. I just want to use faker to verify proper handling of the characters.

**Comment by Marak** [comment]
I want to add the additional data, but basic translation of the text shows
some strange / political words.

I don't want to cause any issues.

**Comment by Marak** [comment]
@lonso -

Can you comment on the source of this data?

**Comment by lonso** [comment]
@Marak let me try.
But how can i do?
just translate that words?

**Comment by Marak** [comment]
@lonso -

When I google translated the words, they seemed strange. A lot of the words related to possible geopolitical issues. I don't speak any Chinese, so I really have no clue.

**Comment by louy2** [comment]
I am a Chinese native speaker and I can confirm that the lorem word list, although containing geopolitical words, is probably not intentionally doing so. It is a list of two-char words sorted alphabetically in Pinyin (a romanization system for Chinese), ranging from "a" to part of "bing". I agree it can be improved.  In fact, due to the fact that Chinese text differs Latin text in formation (no spaces between words, different punctuation glyphs, to name a couple) , the result from using the Latin lorem on this word list would probably be weird.

The phone number update is a nice one though. Too bad they're in the same commit. Another lesson case for better splitting commits.

**Comment by franklinyu** [comment]
Chinese native speaker here. Basically agree with @louy2. Words that unknown to me:

* `暗 *` (a typo?)
* `澳毛`
* `澳抗`
* `比比`

And `瘪三` is derogatory and informal. I'm more worrying about the Chinese lorem being weird, as mentioned by @louy2.

**Comment by Marak** [comment]
I'm tempted to just merge this.

Any objections?

**Comment by louy2** [comment]
As I have mentioned I don't think the Chinese lorem is usable in this form. If you merge this I suggest taking out the Chinese lorem work list afterwards. Here is a proper Chinese lorem generator, just click on the numbers representing requested length: http://www.richyli.com/tool/loremipsum/

**Comment by franklinyu** [comment]
That (Ricky Li) is a decent one, but I'm not sure how does @Marak like the idea of modifying `Lorem` to that extent… We need to somehow tell `Lorem.prototype.words()` not to insert spaces, and maybe to tell `Lorem.prototype.sentence()` to end the sentence in random punctuation.

**Comment by Marak** [comment]
I speak no Chinese, so it's difficult for me to give specific feedback here.

I would say try opening a new smaller pull request that adds a smaller set of this data. At least that way we can get something merged.

Closing this PR for now.

**Comment by louy2** [comment]
@franklinyu Yeah, the algorithm would be so different that I think it warrants a separate function like `Lorem.CJK()`. The phone format is still useful though. I'll put that in a separate PR.

**Pull request closed without merging**
