### PR TITLE
[docs] Add jsdoc documentation

### PR DESCRIPTION
**Pull request by ohcibi**
A simple list of all api methods is often not sufficient. Some params
need explanation, some method names are not self explanatory. Plus a
generated documentation can easily be converted into other formats (e.g.
for dash).

For this PR, I've installed jsdoc and added stubs for all existent api
methods. I've tried to annotate all params with their correct type
(there might be mistakes) and wherever there was a comment explaining a
method in the code, I've used that as a description. I also added some
new description to some methods of the address namespace, but I decided
to create a 100% complete API at first when I realized the needed
effort. The default template from jsdoc creates source code listings and
adds links for each method into the source code, which already is pretty
convenient.

I'll continue creating further pull requests, updating the descriptions
when this PR has been accepted.

### CODE REVIEW

**Comment by Marak** [comment]
That's nice.

Have you looked at #170 ?

We've been working on an alternate approach.

**Comment by ohcibi** [comment]
Oh I must have overlooked it. Can I dump mine now? 8-). I personally like jsdoc more as I don't actually need a tool to see the information. Plus JetBrains Webstorm and other IDEs have built-in support for it.

**Comment by Marak** [comment]
Who will maintain these JSDOC annotations when the API is updated?

**Comment by ohcibi** [comment]
The one who updates the API? Hows that different with the other approach?

**Comment by Marak** [comment]
So, not you then?

**Comment by ohcibi** [comment]
Well, not necessarily. But again: does nobody has to maintain the docs with the other approach?

**Comment by Marak** [comment]
@ohcibi -

I thought about this a bit, and this is good. Thank you for taking the time to document every method with JSDOC.

The thing is, I don't like the idea of static documentation that lives in-line with the code as comments. I'd much rather have the api contracts live on the `faker` object itself, so it can be enumerating / reflected across other interfaces. We've got most of this in place already and have a bit of tooling using [mschema](https://github.com/mschema/mschema)

As you have pointed out, JSDOC already has many tools available for it.

The best choice for `faker` is to merge this pull request so developers can utilize the existing JSDOC tool-chain. We will also be implementing `mschema` based documentation with #170 

The only down-side of using both JSDOC and mschema will be some additional code clutter, however with our build processes and general structure of the project I feel it won't be too bad. We'll need to make sure the API methods stay updated, but the `faker` API is actually somewhat stable at this point, so it should be managable.

Thanks again for your contribution @ohcibi. I will review and merge this soon.

**Comment by Marak** [comment]
Merged with https://github.com/Marak/faker.js/commit/90a6a04f9cd4a134fec20949e68beb4baf79bfae

Very nice @ohcibi . We should figure out a place to host these html docs now.

re: #170

**Comment by ohcibi** [comment]
@Marak i've setup a github pages site on my fork. Checkout https://ohcibi.github.io/faker.js - so the hosting part is easy. What we need is a proper build chain. I saw `grunt-gh-pages` for example but as you are currently not using any build tool except for npm I didn't want to decide that just by myself.

An approach for an npm-script could be to simply clone the repo with the `gh-pages` branch checked out into the current clone, generate the docs, push back and remove the `gh-pages` clone.

**Comment by Marak** [comment]
@ohcibi -

Looking into this right now. We are actually using `gulp`, so there is a build tool.

**Comment by Marak** [comment]
@ohcibi -

I was able to use the `gulp` toolchain to automate both the generation and publishing of JSDOCs to github pages.

Results: http://marak.github.io/faker.js/

**Comment by ohcibi** [comment]
@marak Great! How will one contribute to this now? Is generating the docs and pushing the branch automated or will it require two prs?

**Pull request closed without merging**
