### PR TITLE
Feature: add http methods to internet  namespace

### PR DESCRIPTION
**Pull request by ariel-enso**
Expose function **httpMethod** under internet namespace  to return Http Methods (GET, POST, PUT, DELETE, PATCH)
tests included, gulp tasks ran.

### CODE REVIEW

**Comment by ariel-enso** [comment]
@Marak any chance to merge it? 👍

**Comment by Marak** [comment]
@ariel-enso -

Thank you for your contributions.

We can't merge this in it's current state due to modifications of `ReadMe` and `./dist` files. Those files are managed automatically by our release process.

If you can update this PR to only have the actual API changes and not build changes we can merge it.

Thanks again!

**Comment by ariel-enso** [comment]
@Marak done.

**Comment by Marak** [comment]
Thank you for your contribution @ariel-enso 

Merged.

**Pull request merged**
