### PR TITLE
Add nl_BE locale

### PR DESCRIPTION
**Pull request by thomastoye**
Add nl_BE locale (Dutch (Belgium), aka Flemish)

### CODE REVIEW

**Comment by thomastoye** [comment]
@Marak The docs mention a monthly release schedule, but it seems like the last commit was in March. Any chance of merging this soon, or have you abandoned this project?

**Comment by Marak** [comment]
*sigh*.

The last commit was [June 30th](https://github.com/Marak/faker.js/tree/unique), not March.

The docs state, "Major and Minor version releases are **generally** on a monthly schedule."

I appreciate you waiting 7 minutes after your Pull Request was opened to ask me if the project is abandoned. Thank you for your support.

If you want to see your feature jump to the top of the list, please feel free to pledge your support to the project on [Open Collective](https://opencollective.com/fakerjs)

**Comment by thomastoye** [comment]
Sorry if my comment rubbed you the wrong way - I saw the commit history right after I submitted this PR and failed to notice you were working in the `unique` branch. The intention was to publish my own package if this couldn't be merged in the coming months.

**Comment by Marak** [comment]
You should link directly to your own fork via Github. You don't need to publish to NPM. Just use the `repository` field.

https://docs.npmjs.com/files/package.json

**Comment by Marak** [comment]
PR looks OK, but will require removal of duplicate data in order to be merged.

It appears that 1/3 of the PR ( about 1,000 lines ) is duplicate of data already available in faker.

Please resolve, or I will try to resolve later and merge. Thanks.

**Comment by thomastoye** [comment]
I removed the duplicate files with the `nl` locale as a fallback.

**Comment by Marak** [comment]
Looks good, thank you @thomastoye.

Merged.

Will try to have next release out soon.

**Pull request merged**
