### PR TITLE
Remove duplicate data property in object literal

### LINKED ISSUE #183: `bs_noun` defined twice in sk.js
https://github.com/Marak/faker.js/blob/master/lib/locales/sk.js#L2217 and https://github.com/Marak/faker.js/blob/master/lib/locales/sk.js#L2284

Duplicate data property in object literal not allowed in strict mode

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Closes #183

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Failed due to #185

**Comment by TheSharpieOne** [comment]
Reopening to trigger travis to run again

**Comment by TheSharpieOne** [comment]
Reopening to trigger CI to run again

**Comment by Marak** [comment]
Merged.

Thanks!

**Pull request closed without merging**
