### PR TITLE
Bitcoin support

### PR DESCRIPTION
**Pull request by ashpr**
Bitcoin support as requested in issue #285

I wasn't 100% sure on where to apply it. Bitcoin is mostly finance as it's a currency but you could also argue it belongs in internet as it's a 100% internet based service.

Up to discussion...

### CODE REVIEW

**Comment by Marak** [comment]
@ashpr - Looks good!

Merged.

Thank you for your contribution.

**Comment by Marak** [comment]
This is actually not so good.

We aren't using direct calls to `Math.random` anymore in favor of mersenne twister, `faker.random.number`

Also causing some tests to fail. Going to comment it out for now.

**Comment by ashpr** [comment]
Oh dear, sorry about that. I'll take a look soon and iron it out.

**Comment by Marak** [comment]
@ashpr If you have time to change the implementation I'd be glad to merge a new Pull Request.

**Comment by zpiman** [comment]
@ashpr @Marak This is actually critical!!!!! Bitcoin addresses are not as simple! First of all this does not create valid Bitcoin addresses. But that aside, a bitcoin address never contains the uppercase letter "O", uppercase "I", lowercase "l" and the number "0". https://en.bitcoin.it/wiki/Address 

I think it would be worth checking out this in the future https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses

**Comment by johnmaia** [comment]
@zpiman please checkout my PR (#591) where I purpose a fix for this issue.

**Pull request merged**
