### PR TITLE
Add 'setLocale' method to solve problem with ES6 import

### PR DESCRIPTION
**Pull request by IvanGoncharov**
If you do `import * as faker from 'faker'` you can't do `faker.locale = 'uk';` since it produce runtime errors. 

ES6 forbids you to modify properties of top-level important objects and same is also true for TypeScrips.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@Marak can you please review this change. It's only a few line of code but big change for developers who using your library in ES6/TS/Flow projects.

**Comment by Marak** [comment]
I guess that makes sense.

Will review and add to next version.

**Comment by IvanGoncharov** [comment]
@Marak Can you please merge this PR and release a new version?

**Comment by Marak** [comment]
@IvanGoncharov 

Could you add test for this?

**Comment by Marak** [comment]
It seemed like we should merge this ASAP, so I have.

Please try to add tests later if you can.

**Comment by IvanGoncharov** [comment]
@Marak Can you please release new NPM package with this change included?

**Pull request merged**
