### PR TITLE
fixed system.directoryPath and system.filePath

### PR DESCRIPTION
**Pull request by simone-sanfratello**
also gitignore .vscode and package-lock.json

### CODE REVIEW

**Comment by albinotonnina** [comment]
Hi!
Are you planning to merge this one?

**Comment by Marak** [comment]
I cannot merge the PR in it's current state.

Will need only the modified files ( and not the entire project rebuilt )

**Comment by Marak** [comment]
@simone-sanfratello - Yes

**Comment by Marak** [comment]
Just make sure to only request to merge the actual source code files being changed and not the generated `build` or `examples` folders. 

Thank you.

**Comment by simone-sanfratello** [comment]
done here https://github.com/Marak/faker.js/pull/691

**Pull request closed without merging**
