### PR TITLE
[FIX][#1204] Updated PlaceIMG catgories to reflect changes 

### PR DESCRIPTION
**Pull request by MilosPaunovic**
[PlaceIMG](https://placeimg.com/) changed their categories, so this change reflects that.

### CODE REVIEW

**Comment by piranna** [comment]
For cats there's another specific placeholder, probably we can use it.

https://placekitten.com/

**Comment by MilosPaunovic** [comment]
This is a much bigger issue than my current fix, so this PR will be closed.

A lot of functions rely on removed categories from PlaceIMG. I could tackle the entire thing if that is okay with you @Marak and if you think it makes sense?

**Comment by MilosPaunovic** [comment]
This is a much bigger issue than my current fix, so this PR will be closed.

A lot of functions rely on removed categories from PlaceIMG. I could tackle the entire thing if that is okay with you @Marak and if you think it makes sense?

**Comment by raffobaffo** [comment]
Hi! How's the status of this? I'm also kinda of frustrated by setting `"business"` and getting smiling faces 😅

**Pull request closed without merging**
