### PR TITLE
fix: remove mrmartineau

### PR DESCRIPTION
**Pull request by mrmartineau**
# 🙅‍♂️
This PR removes references to my image from the repo

### CODE REVIEW

**Comment by mrmartineau** [comment]
@Marak any danger of merging this PR. Would love to get myself removed.

**Comment by Marak** [comment]
@mrmartineau  -

Thank you for your contribution.

All Pull Requests to `faker.js` must be done *without* modification of the build files. I cannot merge a 79 file change when only a few files have actually been changed.

Closing for now. Please feel to re-open the PR and only modify the files which are actually changed.

**Comment by mrmartineau** [comment]
@Marak can you explain what needs to be done then? If I want to remove my image, what should I do?

**Comment by Marak** [comment]
https://github.com/Marak/faker.js/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
