### PR TITLE
[fix] Faker.fake("{{random.uuid}}") throws error in version 3.1

### PR DESCRIPTION
**Pull request by skylarstein**
Fix for https://github.com/Marak/faker.js/issues/368

No other Faker.fake("{{random.X}}") values had this issue.

### CODE REVIEW

**Comment by john-kurkowski** [comment]
The error was introduced in #335. Although `window.faker` looks like a stateless global, it actually has internal state via `faker.seed(...)`. Hence my change to use `this.number`.

Rather than undoing #335 in this PR, can `Faker.fake` thread the `this` context through to `replacePlaceholders`?

**Comment by francescomalatesta** [comment]
Hi guys, having the same issue here. What is the situation right now? Any decisions about this PR? :) thx

**Comment by ifraixedes** [comment]
This should be merge, as it's a bug and the PR fix the issue

**Comment by Marak** [comment]
Marked for fixing in the next release.

Since `Faker.faker` is a sugar syntax for the core methods, you can always work-around it by calling the core methods directly.

**Comment by orangewise** [comment]
@Marak any idea on when the next release is due? Would be nice to have this PR merged :)

**Comment by ffffranklin** [comment]
Proposed fix #402 should handle both usecases.

**Comment by Marak** [comment]
Should be resolved with #377 

Published in latest version of faker

**Pull request closed without merging**
