### PR TITLE
Allowed gender passed to name.firstName(gender) to be a string

### LINKED ISSUE #677: Problem with gender
I try to obtain a name with specific gender in NodeJs, but doesn't work.

what am I doing wrong?

```
    let genders = [ 'female' , 'male' ];
    let gender = faker.random.arrayElement(gender);
    let name = faker.name.firstName(genre);
```

### PR DESCRIPTION
**Pull request by NullShock78**
Added a feature where you can pass a string into `faker.name.firstName(gender)` 

- Accepts "male" or "female" in English (all other strings fall back to non-gendered names)
- Case insensitive 
- Unit tests created for new inputs

Fixes #677

### CODE REVIEW

**Comment by SanchitB23** [comment]
Does not work, still shows random male/female names

**Comment by Jcharloi** [comment]
Saw it on Google : ```faker.name.firstNameFemale()` but does not works either. -_-

**Comment by drdynscript** [comment]
`private createUsers = async () => {
    const promises = [];

    promises.push(this.userCreate('drdynscript@gmail.com', 'nmdgent007!', 'administrator', 'Philippe', 'De Pauw - Waterschoot', 'https://scontent-bru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/42580828_10214673932035654_3017264055002857472_n.jpg?_nc_cat=104&_nc_sid=dbb9e7&_nc_oc=AQky73y198J_4BGQhgdOfxD6Wp762ihGE764K2U9j8gjJCbkSJrM_yu11FG0Q9HOuJY&_nc_ht=scontent-bru2-1.xx&_nc_tp=6&oh=b25900e692c0a512d7751430fdcc341b&oe=5E9D1176'));

    for (let i = 0; i < 30; i++) {
      const gender = Math.round(Math.random());
      promises.push(this.userCreate(faker.internet.email(), 'nmdgent007!', 'user', faker.name.firstName(gender), faker.name.lastName(gender), faker.internet.avatar()));
    }
    await Promise.all(promises);
  }`

**Comment by Marak** [comment]
Thank you for your contribution @NullShock78 !

Merged.

**Pull request merged**
