### PR TITLE
Corrections in Readme file

### PR DESCRIPTION
**Pull request by CosmicYogi**
Readme.md was having small errors regarding getting started code.
like `var randomName = faker.name.findName()`
which should be `var randomName = faker.Name.findName()`

### CODE REVIEW

**Comment by Marak** [comment]
No, this is not correct.

**Comment by CosmicYogi** [comment]
Am attaching the screenshots from the project I am working on please have a look at them.
You will see when used with `name.findName()` it would give an error and it would work properly when used with `Name.findName()`.
screen shot 2018-06-13 at 1 58 38 pm
screen shot 2018-06-13 at 1 59 09 pm

**Comment by Marak** [comment]
`Faker` is not `faker`.

You are using wrong project.

**Comment by CosmicYogi** [comment]
Ohhhh.
I'm sorry for such a silly thing.

**Pull request closed without merging**
