### PR TITLE
Normalize locale codes and titles

### PR DESCRIPTION
**Pull request by oscarmarcelo**
There are some inconsistencies between locales. This PR aims to fix them:

- Normalize locale titles to (loosely) comply with Unicode BCP 47. All locale titles are now in the format `<Language> (<Country> <Region or Variant>)`. Also, "Greek" title is now in english;
- Add missing locales to `./locale` folder, since some of the locales in `./lib/locales` weren't available in `./locale`, making the user unable to load them independently;
- Normalize "English (Australia Ocker)" country code across the repository (`en_AU_ocker`).

### CODE REVIEW

**Comment by Marak** [comment]
@oscarmarcelo -

Thank you for your contribution.

Unfortunately, Travis is telling us the tests are failing. I cannot merge PRs into `faker.js` that cause the tests to fail. 

Please feel free to update the PR to get the tests passing.

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Comment by Moosh-be** [comment]
I've try to fix via #955

**Pull request merged**
